# Generated by Django 3.2.3 on 2021-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210610_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='bachelor_major',
            field=models.CharField(blank=True, max_length=135, verbose_name='本科专业'),
        ),
        migrations.AddField(
            model_name='resume',
            name='doctor_major',
            field=models.CharField(blank=True, max_length=135, verbose_name='博士专业'),
        ),
        migrations.AddField(
            model_name='resume',
            name='master_major',
            field=models.CharField(blank=True, max_length=135, verbose_name='研究生专业'),
        ),
    ]
